### ISSUE TITLE
Is there a way to only show containers I started?

### ISSUE THREAD

**Issue by hekaldama** [open-policy-agent/docker-authz-plugin#2]
Trying to figure out how to use a docker swarm cluster with this plugin. I would like to be able to only see the containers I started or own. Can you think of a way to do this with this plugin? Would I need to submit PRs for `AuthZRes()`?

Thanks.

**Comment by tsandall** [comment]
AFAIK, Docker doesn't allow plugins to modify the request or response, so at this time, what you're asking for is not possible.

That being said, if Docker did allow plugins to modify the response, what you suggested would be correct. For example, we could update `AuthZRes()` to apply a set of changes returned by a query to OPA. The policy could define the set of changes as JSON Patch operations on the response object. The same would work for requests.

**Comment by hekaldama** [comment]
Thanks for the reply and that makes sense if the feature becomes available in docker.
